# Generated by Django 2.2.3 on 2019-07-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190730_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='added_at',
        ),
        migrations.AlterField(
            model_name='thing',
            name='text',
            field=models.TextField(default=' '),
        ),
    ]
